name: CI/CD Pipeline to Docker Hub

on:
  push:
    branches:
      - main
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Check out the code
        uses: actions/checkout@v2

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aspnet-app:${{ github.sha }} .

      # Publicar a imagem Docker no Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aspnet-app:${{ github.sha }}
